/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WtxcRouteImport } from './routes/wtxc'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ValueRouteImport } from './routes/value'
import { Route as TrollsRouteImport } from './routes/trolls'
import { Route as TokenomicsRouteImport } from './routes/tokenomics'
import { Route as TexasRouteImport } from './routes/texas'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProofOfWorkRouteImport } from './routes/proof-of-work'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as InTheNewsRouteImport } from './routes/in-the-news'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as TheCaseForTEXITcoinDothtmlRouteImport } from './routes/The-Case-for-TEXITcoin[.]html'
import { Route as NewsAndUpdatesDothtmlRouteImport } from './routes/News-and-Updates[.]html'
import { Route as MeetTheTeamDothtmlRouteImport } from './routes/Meet-the-Team[.]html'
import { Route as DiscoverTEXITcoinDothtmlRouteImport } from './routes/Discover-TEXITcoin[.]html'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const WtxcRoute = WtxcRouteImport.update({
  id: '/wtxc',
  path: '/wtxc',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const TrollsRoute = TrollsRouteImport.update({
  id: '/trolls',
  path: '/trolls',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenomicsRoute = TokenomicsRouteImport.update({
  id: '/tokenomics',
  path: '/tokenomics',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasRoute = TexasRouteImport.update({
  id: '/texas',
  path: '/texas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofOfWorkRoute = ProofOfWorkRouteImport.update({
  id: '/proof-of-work',
  path: '/proof-of-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InTheNewsRoute = InTheNewsRouteImport.update({
  id: '/in-the-news',
  path: '/in-the-news',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const TheCaseForTEXITcoinDothtmlRoute =
  TheCaseForTEXITcoinDothtmlRouteImport.update({
    id: '/The-Case-for-TEXITcoin.html',
    path: '/The-Case-for-TEXITcoin.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsAndUpdatesDothtmlRoute = NewsAndUpdatesDothtmlRouteImport.update({
  id: '/News-and-Updates.html',
  path: '/News-and-Updates.html',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheTeamDothtmlRoute = MeetTheTeamDothtmlRouteImport.update({
  id: '/Meet-the-Team.html',
  path: '/Meet-the-Team.html',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverTEXITcoinDothtmlRoute =
  DiscoverTEXITcoinDothtmlRouteImport.update({
    id: '/Discover-TEXITcoin.html',
    path: '/Discover-TEXITcoin.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Discover-TEXITcoin.html': typeof DiscoverTEXITcoinDothtmlRoute
  '/Meet-the-Team.html': typeof MeetTheTeamDothtmlRoute
  '/News-and-Updates.html': typeof NewsAndUpdatesDothtmlRoute
  '/The-Case-for-TEXITcoin.html': typeof TheCaseForTEXITcoinDothtmlRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/buy': typeof BuyRoute
  '/currency': typeof CurrencyRoute
  '/disclosures': typeof DisclosuresRoute
  '/faq': typeof FaqRoute
  '/in-the-news': typeof InTheNewsRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/merch': typeof MerchRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-work': typeof ProofOfWorkRoute
  '/roadmap': typeof RoadmapRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/texas': typeof TexasRoute
  '/tokenomics': typeof TokenomicsRoute
  '/trolls': typeof TrollsRoute
  '/value': typeof ValueRoute
  '/videos': typeof VideosRoute
  '/wallets': typeof WalletsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/wtxc': typeof WtxcRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Discover-TEXITcoin.html': typeof DiscoverTEXITcoinDothtmlRoute
  '/Meet-the-Team.html': typeof MeetTheTeamDothtmlRoute
  '/News-and-Updates.html': typeof NewsAndUpdatesDothtmlRoute
  '/The-Case-for-TEXITcoin.html': typeof TheCaseForTEXITcoinDothtmlRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/buy': typeof BuyRoute
  '/currency': typeof CurrencyRoute
  '/disclosures': typeof DisclosuresRoute
  '/faq': typeof FaqRoute
  '/in-the-news': typeof InTheNewsRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/merch': typeof MerchRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-work': typeof ProofOfWorkRoute
  '/roadmap': typeof RoadmapRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/texas': typeof TexasRoute
  '/tokenomics': typeof TokenomicsRoute
  '/trolls': typeof TrollsRoute
  '/value': typeof ValueRoute
  '/videos': typeof VideosRoute
  '/wallets': typeof WalletsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/wtxc': typeof WtxcRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Discover-TEXITcoin.html': typeof DiscoverTEXITcoinDothtmlRoute
  '/Meet-the-Team.html': typeof MeetTheTeamDothtmlRoute
  '/News-and-Updates.html': typeof NewsAndUpdatesDothtmlRoute
  '/The-Case-for-TEXITcoin.html': typeof TheCaseForTEXITcoinDothtmlRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/buy': typeof BuyRoute
  '/currency': typeof CurrencyRoute
  '/disclosures': typeof DisclosuresRoute
  '/faq': typeof FaqRoute
  '/in-the-news': typeof InTheNewsRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/merch': typeof MerchRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-work': typeof ProofOfWorkRoute
  '/roadmap': typeof RoadmapRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/texas': typeof TexasRoute
  '/tokenomics': typeof TokenomicsRoute
  '/trolls': typeof TrollsRoute
  '/value': typeof ValueRoute
  '/videos': typeof VideosRoute
  '/wallets': typeof WalletsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/wtxc': typeof WtxcRoute
  '/blog_/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Discover-TEXITcoin.html'
    | '/Meet-the-Team.html'
    | '/News-and-Updates.html'
    | '/The-Case-for-TEXITcoin.html'
    | '/blog'
    | '/build'
    | '/buy'
    | '/currency'
    | '/disclosures'
    | '/faq'
    | '/in-the-news'
    | '/leadership'
    | '/legal'
    | '/merch'
    | '/press'
    | '/privacy'
    | '/proof-of-work'
    | '/roadmap'
    | '/team'
    | '/terms'
    | '/texas'
    | '/tokenomics'
    | '/trolls'
    | '/value'
    | '/videos'
    | '/wallets'
    | '/whitepaper'
    | '/wtxc'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Discover-TEXITcoin.html'
    | '/Meet-the-Team.html'
    | '/News-and-Updates.html'
    | '/The-Case-for-TEXITcoin.html'
    | '/blog'
    | '/build'
    | '/buy'
    | '/currency'
    | '/disclosures'
    | '/faq'
    | '/in-the-news'
    | '/leadership'
    | '/legal'
    | '/merch'
    | '/press'
    | '/privacy'
    | '/proof-of-work'
    | '/roadmap'
    | '/team'
    | '/terms'
    | '/texas'
    | '/tokenomics'
    | '/trolls'
    | '/value'
    | '/videos'
    | '/wallets'
    | '/whitepaper'
    | '/wtxc'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/Discover-TEXITcoin.html'
    | '/Meet-the-Team.html'
    | '/News-and-Updates.html'
    | '/The-Case-for-TEXITcoin.html'
    | '/blog'
    | '/build'
    | '/buy'
    | '/currency'
    | '/disclosures'
    | '/faq'
    | '/in-the-news'
    | '/leadership'
    | '/legal'
    | '/merch'
    | '/press'
    | '/privacy'
    | '/proof-of-work'
    | '/roadmap'
    | '/team'
    | '/terms'
    | '/texas'
    | '/tokenomics'
    | '/trolls'
    | '/value'
    | '/videos'
    | '/wallets'
    | '/whitepaper'
    | '/wtxc'
    | '/blog_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverTEXITcoinDothtmlRoute: typeof DiscoverTEXITcoinDothtmlRoute
  MeetTheTeamDothtmlRoute: typeof MeetTheTeamDothtmlRoute
  NewsAndUpdatesDothtmlRoute: typeof NewsAndUpdatesDothtmlRoute
  TheCaseForTEXITcoinDothtmlRoute: typeof TheCaseForTEXITcoinDothtmlRoute
  BlogRoute: typeof BlogRoute
  BuildRoute: typeof BuildRoute
  BuyRoute: typeof BuyRoute
  CurrencyRoute: typeof CurrencyRoute
  DisclosuresRoute: typeof DisclosuresRoute
  FaqRoute: typeof FaqRoute
  InTheNewsRoute: typeof InTheNewsRoute
  LeadershipRoute: typeof LeadershipRoute
  LegalRoute: typeof LegalRoute
  MerchRoute: typeof MerchRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ProofOfWorkRoute: typeof ProofOfWorkRoute
  RoadmapRoute: typeof RoadmapRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TexasRoute: typeof TexasRoute
  TokenomicsRoute: typeof TokenomicsRoute
  TrollsRoute: typeof TrollsRoute
  ValueRoute: typeof ValueRoute
  VideosRoute: typeof VideosRoute
  WalletsRoute: typeof WalletsRoute
  WhitepaperRoute: typeof WhitepaperRoute
  WtxcRoute: typeof WtxcRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wtxc': {
      id: '/wtxc'
      path: '/wtxc'
      fullPath: '/wtxc'
      preLoaderRoute: typeof WtxcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trolls': {
      id: '/trolls'
      path: '/trolls'
      fullPath: '/trolls'
      preLoaderRoute: typeof TrollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenomics': {
      id: '/tokenomics'
      path: '/tokenomics'
      fullPath: '/tokenomics'
      preLoaderRoute: typeof TokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texas': {
      id: '/texas'
      path: '/texas'
      fullPath: '/texas'
      preLoaderRoute: typeof TexasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-of-work': {
      id: '/proof-of-work'
      path: '/proof-of-work'
      fullPath: '/proof-of-work'
      preLoaderRoute: typeof ProofOfWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-the-news': {
      id: '/in-the-news'
      path: '/in-the-news'
      fullPath: '/in-the-news'
      preLoaderRoute: typeof InTheNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/The-Case-for-TEXITcoin.html': {
      id: '/The-Case-for-TEXITcoin.html'
      path: '/The-Case-for-TEXITcoin.html'
      fullPath: '/The-Case-for-TEXITcoin.html'
      preLoaderRoute: typeof TheCaseForTEXITcoinDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/News-and-Updates.html': {
      id: '/News-and-Updates.html'
      path: '/News-and-Updates.html'
      fullPath: '/News-and-Updates.html'
      preLoaderRoute: typeof NewsAndUpdatesDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Meet-the-Team.html': {
      id: '/Meet-the-Team.html'
      path: '/Meet-the-Team.html'
      fullPath: '/Meet-the-Team.html'
      preLoaderRoute: typeof MeetTheTeamDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Discover-TEXITcoin.html': {
      id: '/Discover-TEXITcoin.html'
      path: '/Discover-TEXITcoin.html'
      fullPath: '/Discover-TEXITcoin.html'
      preLoaderRoute: typeof DiscoverTEXITcoinDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverTEXITcoinDothtmlRoute: DiscoverTEXITcoinDothtmlRoute,
  MeetTheTeamDothtmlRoute: MeetTheTeamDothtmlRoute,
  NewsAndUpdatesDothtmlRoute: NewsAndUpdatesDothtmlRoute,
  TheCaseForTEXITcoinDothtmlRoute: TheCaseForTEXITcoinDothtmlRoute,
  BlogRoute: BlogRoute,
  BuildRoute: BuildRoute,
  BuyRoute: BuyRoute,
  CurrencyRoute: CurrencyRoute,
  DisclosuresRoute: DisclosuresRoute,
  FaqRoute: FaqRoute,
  InTheNewsRoute: InTheNewsRoute,
  LeadershipRoute: LeadershipRoute,
  LegalRoute: LegalRoute,
  MerchRoute: MerchRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ProofOfWorkRoute: ProofOfWorkRoute,
  RoadmapRoute: RoadmapRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TexasRoute: TexasRoute,
  TokenomicsRoute: TokenomicsRoute,
  TrollsRoute: TrollsRoute,
  ValueRoute: ValueRoute,
  VideosRoute: VideosRoute,
  WalletsRoute: WalletsRoute,
  WhitepaperRoute: WhitepaperRoute,
  WtxcRoute: WtxcRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
