/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoomRouteImport } from './routes/zoom'
import { Route as WtxcRouteImport } from './routes/wtxc'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ValueRouteImport } from './routes/value'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrollsRouteImport } from './routes/trolls'
import { Route as TokenomicsRouteImport } from './routes/tokenomics'
import { Route as TexitRouteImport } from './routes/texit'
import { Route as TexasRouteImport } from './routes/texas'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecAndCryptoRouteImport } from './routes/sec-and-crypto'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScreenplayRouteImport } from './routes/screenplay'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProofOfWorkRouteImport } from './routes/proof-of-work'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as MineRouteImport } from './routes/mine'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as InTheNewsRouteImport } from './routes/in-the-news'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as ClarityRouteImport } from './routes/clarity'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BobbyRouteImport } from './routes/bobby'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TheCaseForTEXITcoinDothtmlRouteImport } from './routes/The-Case-for-TEXITcoin[.]html'
import { Route as NewsAndUpdatesDothtmlRouteImport } from './routes/News-and-Updates[.]html'
import { Route as MeetTheTeamDothtmlRouteImport } from './routes/Meet-the-Team[.]html'
import { Route as DiscoverTEXITcoinDothtmlRouteImport } from './routes/Discover-TEXITcoin[.]html'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZoomSlugRouteImport } from './routes/zoom_.$slug'
import { Route as ScreenplaySeasonRouteImport } from './routes/screenplay_.$season'
import { Route as MarketSlugRouteImport } from './routes/market_.$slug'
import { Route as LegalArizonaRouteImport } from './routes/legal_.arizona'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AuthenticatedScreenplayAdminRouteImport } from './routes/_authenticated/screenplay-admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicSendDraftRouteImport } from './routes/api/public/send-draft'
import { Route as ApiPublicLegalFeesRouteImport } from './routes/api/public/legal-fees'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicNotifyNewContentRouteImport } from './routes/api/public/notify/new-content'
import { Route as ApiPublicIpfsCidRouteImport } from './routes/api/public/ipfs.$cid'

const ZoomRoute = ZoomRouteImport.update({
  id: '/zoom',
  path: '/zoom',
  getParentRoute: () => rootRouteImport,
} as any)
const WtxcRoute = WtxcRouteImport.update({
  id: '/wtxc',
  path: '/wtxc',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrollsRoute = TrollsRouteImport.update({
  id: '/trolls',
  path: '/trolls',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenomicsRoute = TokenomicsRouteImport.update({
  id: '/tokenomics',
  path: '/tokenomics',
  getParentRoute: () => rootRouteImport,
} as any)
const TexitRoute = TexitRouteImport.update({
  id: '/texit',
  path: '/texit',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasRoute = TexasRouteImport.update({
  id: '/texas',
  path: '/texas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecAndCryptoRoute = SecAndCryptoRouteImport.update({
  id: '/sec-and-crypto',
  path: '/sec-and-crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenplayRoute = ScreenplayRouteImport.update({
  id: '/screenplay',
  path: '/screenplay',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofOfWorkRoute = ProofOfWorkRouteImport.update({
  id: '/proof-of-work',
  path: '/proof-of-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const MineRoute = MineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InTheNewsRoute = InTheNewsRouteImport.update({
  id: '/in-the-news',
  path: '/in-the-news',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarityRoute = ClarityRouteImport.update({
  id: '/clarity',
  path: '/clarity',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BobbyRoute = BobbyRouteImport.update({
  id: '/bobby',
  path: '/bobby',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TheCaseForTEXITcoinDothtmlRoute =
  TheCaseForTEXITcoinDothtmlRouteImport.update({
    id: '/The-Case-for-TEXITcoin.html',
    path: '/The-Case-for-TEXITcoin.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsAndUpdatesDothtmlRoute = NewsAndUpdatesDothtmlRouteImport.update({
  id: '/News-and-Updates.html',
  path: '/News-and-Updates.html',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheTeamDothtmlRoute = MeetTheTeamDothtmlRouteImport.update({
  id: '/Meet-the-Team.html',
  path: '/Meet-the-Team.html',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverTEXITcoinDothtmlRoute =
  DiscoverTEXITcoinDothtmlRouteImport.update({
    id: '/Discover-TEXITcoin.html',
    path: '/Discover-TEXITcoin.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoomSlugRoute = ZoomSlugRouteImport.update({
  id: '/zoom_/$slug',
  path: '/zoom/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenplaySeasonRoute = ScreenplaySeasonRouteImport.update({
  id: '/screenplay_/$season',
  path: '/screenplay/$season',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSlugRoute = MarketSlugRouteImport.update({
  id: '/market_/$slug',
  path: '/market/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalArizonaRoute = LegalArizonaRouteImport.update({
  id: '/legal_/arizona',
  path: '/legal/arizona',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScreenplayAdminRoute =
  AuthenticatedScreenplayAdminRouteImport.update({
    id: '/screenplay-admin',
    path: '/screenplay-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDraftRoute = ApiPublicSendDraftRouteImport.update({
  id: '/api/public/send-draft',
  path: '/api/public/send-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLegalFeesRoute = ApiPublicLegalFeesRouteImport.update({
  id: '/api/public/legal-fees',
  path: '/api/public/legal-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotifyNewContentRoute =
  ApiPublicNotifyNewContentRouteImport.update({
    id: '/api/public/notify/new-content',
    path: '/api/public/notify/new-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIpfsCidRoute = ApiPublicIpfsCidRouteImport.update({
  id: '/api/public/ipfs/$cid',
  path: '/api/public/ipfs/$cid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Discover-TEXITcoin.html': typeof DiscoverTEXITcoinDothtmlRoute
  '/Meet-the-Team.html': typeof MeetTheTeamDothtmlRoute
  '/News-and-Updates.html': typeof NewsAndUpdatesDothtmlRoute
  '/The-Case-for-TEXITcoin.html': typeof TheCaseForTEXITcoinDothtmlRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/bobby': typeof BobbyRoute
  '/build': typeof BuildRoute
  '/buy': typeof BuyRoute
  '/clarity': typeof ClarityRoute
  '/currency': typeof CurrencyRoute
  '/disclosures': typeof DisclosuresRoute
  '/faq': typeof FaqRoute
  '/in-the-news': typeof InTheNewsRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/market': typeof MarketRoute
  '/mcp': typeof McpRoute
  '/merch': typeof MerchRoute
  '/mine': typeof MineRoute
  '/philosophy': typeof PhilosophyRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-work': typeof ProofOfWorkRoute
  '/roadmap': typeof RoadmapRoute
  '/screenplay': typeof ScreenplayRoute
  '/search': typeof SearchRoute
  '/sec-and-crypto': typeof SecAndCryptoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/texas': typeof TexasRoute
  '/texit': typeof TexitRoute
  '/tokenomics': typeof TokenomicsRoute
  '/trolls': typeof TrollsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/value': typeof ValueRoute
  '/videos': typeof VideosRoute
  '/wallets': typeof WalletsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/wtxc': typeof WtxcRoute
  '/zoom': typeof ZoomRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/screenplay-admin': typeof AuthenticatedScreenplayAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/arizona': typeof LegalArizonaRoute
  '/market/$slug': typeof MarketSlugRoute
  '/screenplay/$season': typeof ScreenplaySeasonRoute
  '/zoom/$slug': typeof ZoomSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/legal-fees': typeof ApiPublicLegalFeesRoute
  '/api/public/send-draft': typeof ApiPublicSendDraftRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/ipfs/$cid': typeof ApiPublicIpfsCidRoute
  '/api/public/notify/new-content': typeof ApiPublicNotifyNewContentRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Discover-TEXITcoin.html': typeof DiscoverTEXITcoinDothtmlRoute
  '/Meet-the-Team.html': typeof MeetTheTeamDothtmlRoute
  '/News-and-Updates.html': typeof NewsAndUpdatesDothtmlRoute
  '/The-Case-for-TEXITcoin.html': typeof TheCaseForTEXITcoinDothtmlRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/bobby': typeof BobbyRoute
  '/build': typeof BuildRoute
  '/buy': typeof BuyRoute
  '/clarity': typeof ClarityRoute
  '/currency': typeof CurrencyRoute
  '/disclosures': typeof DisclosuresRoute
  '/faq': typeof FaqRoute
  '/in-the-news': typeof InTheNewsRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/market': typeof MarketRoute
  '/mcp': typeof McpRoute
  '/merch': typeof MerchRoute
  '/mine': typeof MineRoute
  '/philosophy': typeof PhilosophyRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-work': typeof ProofOfWorkRoute
  '/roadmap': typeof RoadmapRoute
  '/screenplay': typeof ScreenplayRoute
  '/search': typeof SearchRoute
  '/sec-and-crypto': typeof SecAndCryptoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/texas': typeof TexasRoute
  '/texit': typeof TexitRoute
  '/tokenomics': typeof TokenomicsRoute
  '/trolls': typeof TrollsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/value': typeof ValueRoute
  '/videos': typeof VideosRoute
  '/wallets': typeof WalletsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/wtxc': typeof WtxcRoute
  '/zoom': typeof ZoomRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/screenplay-admin': typeof AuthenticatedScreenplayAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/arizona': typeof LegalArizonaRoute
  '/market/$slug': typeof MarketSlugRoute
  '/screenplay/$season': typeof ScreenplaySeasonRoute
  '/zoom/$slug': typeof ZoomSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/legal-fees': typeof ApiPublicLegalFeesRoute
  '/api/public/send-draft': typeof ApiPublicSendDraftRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/ipfs/$cid': typeof ApiPublicIpfsCidRoute
  '/api/public/notify/new-content': typeof ApiPublicNotifyNewContentRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/Discover-TEXITcoin.html': typeof DiscoverTEXITcoinDothtmlRoute
  '/Meet-the-Team.html': typeof MeetTheTeamDothtmlRoute
  '/News-and-Updates.html': typeof NewsAndUpdatesDothtmlRoute
  '/The-Case-for-TEXITcoin.html': typeof TheCaseForTEXITcoinDothtmlRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/bobby': typeof BobbyRoute
  '/build': typeof BuildRoute
  '/buy': typeof BuyRoute
  '/clarity': typeof ClarityRoute
  '/currency': typeof CurrencyRoute
  '/disclosures': typeof DisclosuresRoute
  '/faq': typeof FaqRoute
  '/in-the-news': typeof InTheNewsRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/market': typeof MarketRoute
  '/mcp': typeof McpRoute
  '/merch': typeof MerchRoute
  '/mine': typeof MineRoute
  '/philosophy': typeof PhilosophyRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-work': typeof ProofOfWorkRoute
  '/roadmap': typeof RoadmapRoute
  '/screenplay': typeof ScreenplayRoute
  '/search': typeof SearchRoute
  '/sec-and-crypto': typeof SecAndCryptoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/texas': typeof TexasRoute
  '/texit': typeof TexitRoute
  '/tokenomics': typeof TokenomicsRoute
  '/trolls': typeof TrollsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/value': typeof ValueRoute
  '/videos': typeof VideosRoute
  '/wallets': typeof WalletsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/wtxc': typeof WtxcRoute
  '/zoom': typeof ZoomRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/screenplay-admin': typeof AuthenticatedScreenplayAdminRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal_/arizona': typeof LegalArizonaRoute
  '/market_/$slug': typeof MarketSlugRoute
  '/screenplay_/$season': typeof ScreenplaySeasonRoute
  '/zoom_/$slug': typeof ZoomSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/legal-fees': typeof ApiPublicLegalFeesRoute
  '/api/public/send-draft': typeof ApiPublicSendDraftRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/ipfs/$cid': typeof ApiPublicIpfsCidRoute
  '/api/public/notify/new-content': typeof ApiPublicNotifyNewContentRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Discover-TEXITcoin.html'
    | '/Meet-the-Team.html'
    | '/News-and-Updates.html'
    | '/The-Case-for-TEXITcoin.html'
    | '/auth'
    | '/blog'
    | '/bobby'
    | '/build'
    | '/buy'
    | '/clarity'
    | '/currency'
    | '/disclosures'
    | '/faq'
    | '/in-the-news'
    | '/leadership'
    | '/legal'
    | '/live'
    | '/market'
    | '/mcp'
    | '/merch'
    | '/mine'
    | '/philosophy'
    | '/press'
    | '/privacy'
    | '/proof-of-work'
    | '/roadmap'
    | '/screenplay'
    | '/search'
    | '/sec-and-crypto'
    | '/sitemap.xml'
    | '/stats'
    | '/team'
    | '/terms'
    | '/texas'
    | '/texit'
    | '/tokenomics'
    | '/trolls'
    | '/unsubscribe'
    | '/value'
    | '/videos'
    | '/wallets'
    | '/whitepaper'
    | '/wtxc'
    | '/zoom'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/screenplay-admin'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/legal/arizona'
    | '/market/$slug'
    | '/screenplay/$season'
    | '/zoom/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/legal-fees'
    | '/api/public/send-draft'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/api/public/ipfs/$cid'
    | '/api/public/notify/new-content'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Discover-TEXITcoin.html'
    | '/Meet-the-Team.html'
    | '/News-and-Updates.html'
    | '/The-Case-for-TEXITcoin.html'
    | '/auth'
    | '/blog'
    | '/bobby'
    | '/build'
    | '/buy'
    | '/clarity'
    | '/currency'
    | '/disclosures'
    | '/faq'
    | '/in-the-news'
    | '/leadership'
    | '/legal'
    | '/live'
    | '/market'
    | '/mcp'
    | '/merch'
    | '/mine'
    | '/philosophy'
    | '/press'
    | '/privacy'
    | '/proof-of-work'
    | '/roadmap'
    | '/screenplay'
    | '/search'
    | '/sec-and-crypto'
    | '/sitemap.xml'
    | '/stats'
    | '/team'
    | '/terms'
    | '/texas'
    | '/texit'
    | '/tokenomics'
    | '/trolls'
    | '/unsubscribe'
    | '/value'
    | '/videos'
    | '/wallets'
    | '/whitepaper'
    | '/wtxc'
    | '/zoom'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/screenplay-admin'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/legal/arizona'
    | '/market/$slug'
    | '/screenplay/$season'
    | '/zoom/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/legal-fees'
    | '/api/public/send-draft'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/api/public/ipfs/$cid'
    | '/api/public/notify/new-content'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/Discover-TEXITcoin.html'
    | '/Meet-the-Team.html'
    | '/News-and-Updates.html'
    | '/The-Case-for-TEXITcoin.html'
    | '/auth'
    | '/blog'
    | '/bobby'
    | '/build'
    | '/buy'
    | '/clarity'
    | '/currency'
    | '/disclosures'
    | '/faq'
    | '/in-the-news'
    | '/leadership'
    | '/legal'
    | '/live'
    | '/market'
    | '/mcp'
    | '/merch'
    | '/mine'
    | '/philosophy'
    | '/press'
    | '/privacy'
    | '/proof-of-work'
    | '/roadmap'
    | '/screenplay'
    | '/search'
    | '/sec-and-crypto'
    | '/sitemap.xml'
    | '/stats'
    | '/team'
    | '/terms'
    | '/texas'
    | '/texit'
    | '/tokenomics'
    | '/trolls'
    | '/unsubscribe'
    | '/value'
    | '/videos'
    | '/wallets'
    | '/whitepaper'
    | '/wtxc'
    | '/zoom'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/screenplay-admin'
    | '/blog_/$slug'
    | '/email/unsubscribe'
    | '/legal_/arizona'
    | '/market_/$slug'
    | '/screenplay_/$season'
    | '/zoom_/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/legal-fees'
    | '/api/public/send-draft'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/api/public/ipfs/$cid'
    | '/api/public/notify/new-content'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DiscoverTEXITcoinDothtmlRoute: typeof DiscoverTEXITcoinDothtmlRoute
  MeetTheTeamDothtmlRoute: typeof MeetTheTeamDothtmlRoute
  NewsAndUpdatesDothtmlRoute: typeof NewsAndUpdatesDothtmlRoute
  TheCaseForTEXITcoinDothtmlRoute: typeof TheCaseForTEXITcoinDothtmlRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  BobbyRoute: typeof BobbyRoute
  BuildRoute: typeof BuildRoute
  BuyRoute: typeof BuyRoute
  ClarityRoute: typeof ClarityRoute
  CurrencyRoute: typeof CurrencyRoute
  DisclosuresRoute: typeof DisclosuresRoute
  FaqRoute: typeof FaqRoute
  InTheNewsRoute: typeof InTheNewsRoute
  LeadershipRoute: typeof LeadershipRoute
  LegalRoute: typeof LegalRoute
  LiveRoute: typeof LiveRoute
  MarketRoute: typeof MarketRoute
  McpRoute: typeof McpRoute
  MerchRoute: typeof MerchRoute
  MineRoute: typeof MineRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ProofOfWorkRoute: typeof ProofOfWorkRoute
  RoadmapRoute: typeof RoadmapRoute
  ScreenplayRoute: typeof ScreenplayRoute
  SearchRoute: typeof SearchRoute
  SecAndCryptoRoute: typeof SecAndCryptoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TexasRoute: typeof TexasRoute
  TexitRoute: typeof TexitRoute
  TokenomicsRoute: typeof TokenomicsRoute
  TrollsRoute: typeof TrollsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ValueRoute: typeof ValueRoute
  VideosRoute: typeof VideosRoute
  WalletsRoute: typeof WalletsRoute
  WhitepaperRoute: typeof WhitepaperRoute
  WtxcRoute: typeof WtxcRoute
  ZoomRoute: typeof ZoomRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LegalArizonaRoute: typeof LegalArizonaRoute
  MarketSlugRoute: typeof MarketSlugRoute
  ScreenplaySeasonRoute: typeof ScreenplaySeasonRoute
  ZoomSlugRoute: typeof ZoomSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicLegalFeesRoute: typeof ApiPublicLegalFeesRoute
  ApiPublicSendDraftRoute: typeof ApiPublicSendDraftRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicIpfsCidRoute: typeof ApiPublicIpfsCidRoute
  ApiPublicNotifyNewContentRoute: typeof ApiPublicNotifyNewContentRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoom': {
      id: '/zoom'
      path: '/zoom'
      fullPath: '/zoom'
      preLoaderRoute: typeof ZoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wtxc': {
      id: '/wtxc'
      path: '/wtxc'
      fullPath: '/wtxc'
      preLoaderRoute: typeof WtxcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trolls': {
      id: '/trolls'
      path: '/trolls'
      fullPath: '/trolls'
      preLoaderRoute: typeof TrollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenomics': {
      id: '/tokenomics'
      path: '/tokenomics'
      fullPath: '/tokenomics'
      preLoaderRoute: typeof TokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texit': {
      id: '/texit'
      path: '/texit'
      fullPath: '/texit'
      preLoaderRoute: typeof TexitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texas': {
      id: '/texas'
      path: '/texas'
      fullPath: '/texas'
      preLoaderRoute: typeof TexasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sec-and-crypto': {
      id: '/sec-and-crypto'
      path: '/sec-and-crypto'
      fullPath: '/sec-and-crypto'
      preLoaderRoute: typeof SecAndCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenplay': {
      id: '/screenplay'
      path: '/screenplay'
      fullPath: '/screenplay'
      preLoaderRoute: typeof ScreenplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-of-work': {
      id: '/proof-of-work'
      path: '/proof-of-work'
      fullPath: '/proof-of-work'
      preLoaderRoute: typeof ProofOfWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mine': {
      id: '/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof MineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-the-news': {
      id: '/in-the-news'
      path: '/in-the-news'
      fullPath: '/in-the-news'
      preLoaderRoute: typeof InTheNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarity': {
      id: '/clarity'
      path: '/clarity'
      fullPath: '/clarity'
      preLoaderRoute: typeof ClarityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bobby': {
      id: '/bobby'
      path: '/bobby'
      fullPath: '/bobby'
      preLoaderRoute: typeof BobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/The-Case-for-TEXITcoin.html': {
      id: '/The-Case-for-TEXITcoin.html'
      path: '/The-Case-for-TEXITcoin.html'
      fullPath: '/The-Case-for-TEXITcoin.html'
      preLoaderRoute: typeof TheCaseForTEXITcoinDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/News-and-Updates.html': {
      id: '/News-and-Updates.html'
      path: '/News-and-Updates.html'
      fullPath: '/News-and-Updates.html'
      preLoaderRoute: typeof NewsAndUpdatesDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Meet-the-Team.html': {
      id: '/Meet-the-Team.html'
      path: '/Meet-the-Team.html'
      fullPath: '/Meet-the-Team.html'
      preLoaderRoute: typeof MeetTheTeamDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Discover-TEXITcoin.html': {
      id: '/Discover-TEXITcoin.html'
      path: '/Discover-TEXITcoin.html'
      fullPath: '/Discover-TEXITcoin.html'
      preLoaderRoute: typeof DiscoverTEXITcoinDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoom_/$slug': {
      id: '/zoom_/$slug'
      path: '/zoom/$slug'
      fullPath: '/zoom/$slug'
      preLoaderRoute: typeof ZoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenplay_/$season': {
      id: '/screenplay_/$season'
      path: '/screenplay/$season'
      fullPath: '/screenplay/$season'
      preLoaderRoute: typeof ScreenplaySeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market_/$slug': {
      id: '/market_/$slug'
      path: '/market/$slug'
      fullPath: '/market/$slug'
      preLoaderRoute: typeof MarketSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal_/arizona': {
      id: '/legal_/arizona'
      path: '/legal/arizona'
      fullPath: '/legal/arizona'
      preLoaderRoute: typeof LegalArizonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/screenplay-admin': {
      id: '/_authenticated/screenplay-admin'
      path: '/screenplay-admin'
      fullPath: '/screenplay-admin'
      preLoaderRoute: typeof AuthenticatedScreenplayAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-draft': {
      id: '/api/public/send-draft'
      path: '/api/public/send-draft'
      fullPath: '/api/public/send-draft'
      preLoaderRoute: typeof ApiPublicSendDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/legal-fees': {
      id: '/api/public/legal-fees'
      path: '/api/public/legal-fees'
      fullPath: '/api/public/legal-fees'
      preLoaderRoute: typeof ApiPublicLegalFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/new-content': {
      id: '/api/public/notify/new-content'
      path: '/api/public/notify/new-content'
      fullPath: '/api/public/notify/new-content'
      preLoaderRoute: typeof ApiPublicNotifyNewContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ipfs/$cid': {
      id: '/api/public/ipfs/$cid'
      path: '/api/public/ipfs/$cid'
      fullPath: '/api/public/ipfs/$cid'
      preLoaderRoute: typeof ApiPublicIpfsCidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedScreenplayAdminRoute: typeof AuthenticatedScreenplayAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedScreenplayAdminRoute: AuthenticatedScreenplayAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DiscoverTEXITcoinDothtmlRoute: DiscoverTEXITcoinDothtmlRoute,
  MeetTheTeamDothtmlRoute: MeetTheTeamDothtmlRoute,
  NewsAndUpdatesDothtmlRoute: NewsAndUpdatesDothtmlRoute,
  TheCaseForTEXITcoinDothtmlRoute: TheCaseForTEXITcoinDothtmlRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  BobbyRoute: BobbyRoute,
  BuildRoute: BuildRoute,
  BuyRoute: BuyRoute,
  ClarityRoute: ClarityRoute,
  CurrencyRoute: CurrencyRoute,
  DisclosuresRoute: DisclosuresRoute,
  FaqRoute: FaqRoute,
  InTheNewsRoute: InTheNewsRoute,
  LeadershipRoute: LeadershipRoute,
  LegalRoute: LegalRoute,
  LiveRoute: LiveRoute,
  MarketRoute: MarketRoute,
  McpRoute: McpRoute,
  MerchRoute: MerchRoute,
  MineRoute: MineRoute,
  PhilosophyRoute: PhilosophyRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ProofOfWorkRoute: ProofOfWorkRoute,
  RoadmapRoute: RoadmapRoute,
  ScreenplayRoute: ScreenplayRoute,
  SearchRoute: SearchRoute,
  SecAndCryptoRoute: SecAndCryptoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TexasRoute: TexasRoute,
  TexitRoute: TexitRoute,
  TokenomicsRoute: TokenomicsRoute,
  TrollsRoute: TrollsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ValueRoute: ValueRoute,
  VideosRoute: VideosRoute,
  WalletsRoute: WalletsRoute,
  WhitepaperRoute: WhitepaperRoute,
  WtxcRoute: WtxcRoute,
  ZoomRoute: ZoomRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LegalArizonaRoute: LegalArizonaRoute,
  MarketSlugRoute: MarketSlugRoute,
  ScreenplaySeasonRoute: ScreenplaySeasonRoute,
  ZoomSlugRoute: ZoomSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicLegalFeesRoute: ApiPublicLegalFeesRoute,
  ApiPublicSendDraftRoute: ApiPublicSendDraftRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicIpfsCidRoute: ApiPublicIpfsCidRoute,
  ApiPublicNotifyNewContentRoute: ApiPublicNotifyNewContentRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
